"""create user model

Revision ID: 382e81de46f8
Revises: 
Create Date: 2023-04-25 10:23:41.978137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382e81de46f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_company_id', table_name='company')
    op.drop_index('ix_company_name', table_name='company')
    op.drop_table('company')
    op.drop_index('ix_location_id', table_name='location')
    op.drop_index('ix_location_name', table_name='location')
    op.drop_table('location')
    op.drop_index('ix_jobs_id', table_name='jobs')
    op.drop_index('ix_jobs_title', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('location_id', sa.INTEGER(), nullable=True),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_title', 'jobs', ['title'], unique=False)
    op.create_index('ix_jobs_id', 'jobs', ['id'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_location_name', 'location', ['name'], unique=False)
    op.create_index('ix_location_id', 'location', ['id'], unique=False)
    op.create_table('company',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_name', 'company', ['name'], unique=False)
    op.create_index('ix_company_id', 'company', ['id'], unique=False)
    # ### end Alembic commands ###
